app_version: "0.0.1"
app_name: "Simple-Wedding-Management"
app_port: 9001
app_url: "http://localhost"
environment: "development"
# Database
db_host: "localhost"
db_port: 5432
db_name: "postgres"
db_user: "postgres"
db_password: "mysecretpassword"
# SSO
sso_google_client_id: "1234567890"
sso_google_client_secret: "1234567890"
sso_google_redirect_url: "http://localhost:9001/auth/google/callback"
