app_version: "0.0.1"
app_name: "Simple-Wedding-Management"
app_port: 9001
# Database
db:
  host: "localhost"
  port: 5432
  name: "db_simple_wedding_management"
  user: "postgres"
  password: "password"
